# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Install serve to run the build in a production environment
RUN npm install -g serve

# Expose the port on which the frontend will run
EXPOSE 3000

# Command to serve the app
CMD ["serve", "-s", "build"]
